# Site information
site_name: B-Zone SA:MP Rules

# Theme elements
theme:
  name: material
  favicon: images/favicon.png
  logo: https://res.b-zone.ro/ll/actual.jpg
  icon:
    alternate: material/format-letter-case
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  palette:
    # Auto theme
    - media: "(prefers-color-scheme)"
      primary: black
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Toggle dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Toggle light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to system preferences

# Used plugins
plugins:
  - search
  - i18n:
      docs_structure: suffix
      languages:
        - locale: ro
          default: true
          name: Română
          build: true
        - locale: en
          name: English
          build: true
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

# Used extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

# Copyright elements and cookie settings
copyright: >
  Copyright &copy; 2008-<script>document.write(new Date().getFullYear())</script> B-ZONE All Rights Reserved
  <br/><a href="#__consent">Change cookie settings</a>

# Custom css
extra_css:
  - stylesheets/extra.css

# Footer elements
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.b-zone.ro
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@BZoneCommunity
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@bzonero
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/bzonero
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for.

# Navigation
nav:
  - Server Rules:
    - Reguli Generale: server/server-rules.md
  - Faction Rules:
    - Reguli Factiuni: factions/faction-rules.md